// Mirrors scoring-rule-sheet-v0.1.md — single source of truth for the app.
export const SCORING_EVENTS = [
  { key: "stream_tick", label: "Daily stream tick", delta: 3 },
  { key: "top50", label: "Enters national Top 50", delta: 15 },
  { key: "top10", label: "Enters national Top 10", delta: 30 },
  { key: "chart_up", label: "Chart position +1 rank", delta: 2 },
  { key: "chart_down", label: "Chart position -1 rank", delta: -2 },
  { key: "chart_off", label: "Falls off chart", delta: -10 },
  { key: "view_spike", label: "YouTube view spike (+50%)", delta: 8 },
  { key: "inactivity", label: "14 days no activity", delta: -3 },
  { key: "feature", label: "Feature / collab drop", delta: 10 },
  { key: "nomination", label: "Award nomination", delta: 20 },
  { key: "award_win", label: "Award win", delta: 40 },
  { key: "festival", label: "Festival / show announced", delta: 5 },
  { key: "tour", label: "Tour announced", delta: 10 },
  { key: "label_deal", label: "Label signing / major deal", delta: 15 },
  { key: "viral", label: "Verified viral moment", delta: 12 },
  { key: "press_pos", label: "Positive press", delta: 5 },
  { key: "press_neg", label: "Negative press / controversy", delta: -15 },
  { key: "beef", label: "Beef / diss track drop", delta: 8 },
  { key: "hiatus", label: "Hiatus announced", delta: -20 },
  { key: "custom", label: "Custom (set delta manually)", delta: 0 },
];
